In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import os

In [2]:
data=pd.read_csv('./Stress_csv/Stress_u01.csv')
data=data[['level','resp_time']]
data

    level            resp_time
0     4.0  2013-03-27 04:45:45
1     1.0  2013-03-30 22:27:26
2     1.0  2013-03-29 19:45:25
3     4.0  2013-03-28 23:53:09
4     5.0  2013-03-30 00:32:58
5     1.0  2013-03-31 18:49:27
6     2.0  2013-04-01 02:45:54
7     1.0  2013-04-03 06:03:04
8     4.0  2013-04-04 07:28:35
9     4.0  2013-04-05 06:08:42
10    4.0  2013-04-06 01:26:41
11    5.0  2013-04-06 09:39:30
12    1.0  2013-04-07 21:21:54
13    1.0  2013-04-09 04:50:01
14    1.0  2013-04-10 22:33:15
15    2.0  2013-04-10 02:59:22
16    1.0  2013-04-16 04:24:02
17    1.0  2013-04-11 02:03:16
18    1.0  2013-04-12 02:44:19
19    4.0  2013-04-13 22:54:36
20    1.0  2013-04-14 23:14:15
21    1.0  2013-04-16 01:52:24
22    1.0  2013-04-17 04:01:47
23    4.0  2013-04-19 00:32:42
24    4.0  2013-04-20 06:44:52
25    2.0  2013-04-28 07:47:46
26    2.0  2013-04-28 21:44:49
27    1.0  2013-04-26 18:03:22
28    2.0  2013-04-28 19:34:02
29    3.0  2013-04-29 05:50:08
30    2.0  2013-04-30 05:58:15
31    1.0  2013-05-07 05:04:20

In [3]:
from datetime import datetime
def seconds(time):
    t0=datetime(1970,1,1)
    time = datetime.strptime(time, '%Y-%m-%d %H:%M:%S')
    delta=time-t0
    return delta.total_seconds()
data['time']=data['resp_time'].apply(lambda time: seconds(time))

In [12]:
data

    level            resp_time          time
0     4.0  2013-03-27 04:45:45  1.364360e+09
1     1.0  2013-03-30 22:27:26  1.364682e+09
2     1.0  2013-03-29 19:45:25  1.364586e+09
3     4.0  2013-03-28 23:53:09  1.364515e+09
4     5.0  2013-03-30 00:32:58  1.364604e+09
5     1.0  2013-03-31 18:49:27  1.364756e+09
6     2.0  2013-04-01 02:45:54  1.364784e+09
7     1.0  2013-04-03 06:03:04  1.364969e+09
8     4.0  2013-04-04 07:28:35  1.365061e+09
9     4.0  2013-04-05 06:08:42  1.365142e+09
10    4.0  2013-04-06 01:26:41  1.365212e+09
11    5.0  2013-04-06 09:39:30  1.365241e+09
12    1.0  2013-04-07 21:21:54  1.365370e+09
13    1.0  2013-04-09 04:50:01  1.365483e+09
14    1.0  2013-04-10 22:33:15  1.365633e+09
15    2.0  2013-04-10 02:59:22  1.365563e+09
16    1.0  2013-04-16 04:24:02  1.366086e+09
17    1.0  2013-04-11 02:03:16  1.365646e+09
18    1.0  2013-04-12 02:44:19  1.365735e+09
19    4.0  2013-04-13 22:54:36  1.365894e+09
20    1.0  2013-04-14 23:14:15  1.365981e+09
21    1.0  2013-04-16 01:52:24  1.366077e+09
22    1.0  2013-04-17 04:01:47  1.366171e+09
23    4.0  2013-04-19 00:32:42  1.366332e+09
24    4.0  2013-04-20 06:44:52  1.366440e+09
25    2.0  2013-04-28 07:47:46  1.367135e+09
26    2.0  2013-04-28 21:44:49  1.367185e+09
27    1.0  2013-04-26 18:03:22  1.366999e+09
28    2.0  2013-04-28 19:34:02  1.367178e+09
29    3.0  2013-04-29 05:50:08  1.367215e+09
30    2.0  2013-04-30 05:58:15  1.367301e+09
31    1.0  2013-05-07 05:04:20  1.367903e+09

In [5]:
import pandas as pd
from datetime import datetime
import os
def seconds(time):
        t0=datetime(1970,1,1)
        time = datetime.strptime(time, '%Y-%m-%d %H:%M:%S')
        delta=time-t0
        return delta.total_seconds()
def json_to_csv(i):
    jsonfile='./dataset/EMA/response/Stress'+f'/Stress_u{i:02d}.json'
    csvfile= f'./stress_new/Stress_u{i:02d}.csv'
    print(csvfile)
    df=pd.read_json(jsonfile)

    df=df[['level','resp_time']]
    
    df=df.dropna()
#     df['time']=df['resp_time'].apply(lambda time: seconds(time))
    print(df.info())
    df.to_csv(csvfile)
for i in range(60):
    try:
        json_to_csv(i)
    except:
        pass

./stress_new/Stress_u00.csv
<class 'pandas.core.frame.DataFrame'>
Index: 74 entries, 5 to 78
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   level      74 non-null     float64
 1   resp_time  74 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1)
memory usage: 1.7 KB
None
./stress_new/Stress_u01.csv
<class 'pandas.core.frame.DataFrame'>
Index: 32 entries, 0 to 35
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   level      32 non-null     float64
 1   resp_time  32 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1)
memory usage: 768.0 bytes
None
./stress_new/Stress_u02.csv
<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, 5 to 34
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   level      30 non-null     float64
 1   resp_time  30 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1)
memory usage: 720.0 bytes
None
./stress_new/Stress_u03.csv
<class 'pandas.core.frame.DataFrame'>
Index: 29 entries, 5 to 33
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   level      29 non-null     float64
 1   resp_time  29 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1)
memory usage: 696.0 bytes
None
./stress_new/Stress_u04.csv
<class 'pandas.core.frame.DataFrame'>
Index: 43 entries, 4 to 46
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   level      43 non-null     float64
 1   resp_time  43 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1)
memory usage: 1.0 KB
None
./stress_new/Stress_u05.csv
<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, 5 to 12
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   level      8 non-null      float64
 1   resp_time  8 non-null      datetime64[ns]
dtypes: datetime64[ns](1), float64(1)
memory usage: 192.0 bytes
None
./stress_new/Stress_u06.csv
./stress_new/Stress_u07.csv
<class 'pandas.core.frame.DataFrame'>
Index: 53 entries, 0 to 58
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   level      53 non-null     float64
 1   resp_time  53 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1)
memory usage: 1.2 KB
None
./stress_new/Stress_u08.csv
<class 'pandas.core.frame.DataFrame'>
Index: 90 entries, 2 to 94
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   level      90 non-null     float64
 1   resp_time  90 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1)
memory usage: 2.1 KB
None
./stress_new/Stress_u09.csv
<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, 5 to 7
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   level      3 non-null      float64
 1   resp_time  3 non-null      datetime64[ns]
dtypes: datetime64[ns](1), float64(1)
memory usage: 72.0 bytes
None
./stress_new/Stress_u10.csv
<class 'pandas.core.frame.DataFrame'>
Index: 106 entries, 0 to 111
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   level      106 non-null    float64
 1   resp_time  106 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(1)
memory usage: 2.5 KB
None
./stress_new/Stress_u11.csv
./stress_new/Stress_u12.csv
<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, 0 to 34
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   level      30 non-null     float64
 1   resp_time  30 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1)
memory usage: 720.0 bytes
None
./stress_new/Stress_u13.csv
./stress_new/Stress_u14.csv
<class 'pandas.core.frame.DataFrame'>
Index: 37 entries, 4 to 40
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   level      37 non-null     float64
 1   resp_time  37 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1)
memory usage: 888.0 bytes
None
./stress_new/Stress_u15.csv
<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 6 to 15
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   level      10 non-null     float64
 1   resp_time  10 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1)
memory usage: 240.0 bytes
None
./stress_new/Stress_u16.csv
<class 'pandas.core.frame.DataFrame'>
Index: 107 entries, 0 to 111
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   level      107 non-null    float64
 1   resp_time  107 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(1)
memory usage: 2.5 KB
None
./stress_new/Stress_u17.csv
<class 'pandas.core.frame.DataFrame'>
Index: 42 entries, 5 to 46
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   level      42 non-null     float64
 1   resp_time  42 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1)
memory usage: 1008.0 bytes
None
./stress_new/Stress_u18.csv
<class 'pandas.core.frame.DataFrame'>
Index: 16 entries, 4 to 19
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   level      16 non-null     float64
 1   resp_time  16 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1)
memory usage: 384.0 bytes
None
./stress_new/Stress_u19.csv
<class 'pandas.core.frame.DataFrame'>
Index: 91 entries, 2 to 95
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   level      91 non-null     float64
 1   resp_time  91 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1)
memory usage: 2.1 KB
None
./stress_new/Stress_u20.csv
<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 5 to 14
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   level      10 non-null     float64
 1   resp_time  10 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1)
memory usage: 240.0 bytes
None
./stress_new/Stress_u21.csv
./stress_new/Stress_u22.csv
<class 'pandas.core.frame.DataFrame'>
Index: 55 entries, 0 to 60
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   level      55 non-null     float64
 1   resp_time  55 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1)
memory usage: 1.3 KB
None
./stress_new/Stress_u23.csv
<class 'pandas.core.frame.DataFrame'>
Index: 44 entries, 2 to 48
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   level      44 non-null     float64
 1   resp_time  44 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1)
memory usage: 1.0 KB
None
./stress_new/Stress_u24.csv
<class 'pandas.core.frame.DataFrame'>
Index: 39 entries, 1 to 47
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   level      39 non-null     float64
 1   resp_time  39 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1)
memory usage: 936.0 bytes
None
./stress_new/Stress_u25.csv
<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 5 to 24
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   level      20 non-null     float64
 1   resp_time  20 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1)
memory usage: 480.0 bytes
None
./stress_new/Stress_u26.csv
./stress_new/Stress_u27.csv
<class 'pandas.core.frame.DataFrame'>
Index: 25 entries, 5 to 29
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   level      25 non-null     float64
 1   resp_time  25 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1)
memory usage: 600.0 bytes
None
./stress_new/Stress_u28.csv
./stress_new/Stress_u29.csv
./stress_new/Stress_u30.csv
<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, 5 to 34
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   level      30 non-null     float64
 1   resp_time  30 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1)
memory usage: 720.0 bytes
None
./stress_new/Stress_u31.csv
<class 'pandas.core.frame.DataFrame'>
Index: 12 entries, 5 to 16
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   level      12 non-null     float64
 1   resp_time  12 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1)
memory usage: 288.0 bytes
None
./stress_new/Stress_u32.csv
<class 'pandas.core.frame.DataFrame'>
Index: 66 entries, 7 to 72
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   level      66 non-null     float64
 1   resp_time  66 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1)
memory usage: 1.5 KB
None
./stress_new/Stress_u33.csv
<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 5 to 62
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   level      58 non-null     float64
 1   resp_time  58 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1)
memory usage: 1.4 KB
None
./stress_new/Stress_u34.csv
<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, 0 to 10
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   level      6 non-null      float64
 1   resp_time  6 non-null      datetime64[ns]
dtypes: datetime64[ns](1), float64(1)
memory usage: 144.0 bytes
None
./stress_new/Stress_u35.csv
<class 'pandas.core.frame.DataFrame'>
Index: 39 entries, 5 to 43
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   level      39 non-null     float64
 1   resp_time  39 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1)
memory usage: 936.0 bytes
None
./stress_new/Stress_u36.csv
<class 'pandas.core.frame.DataFrame'>
Index: 56 entries, 1 to 61
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   level      56 non-null     float64
 1   resp_time  56 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1)
memory usage: 1.3 KB
None
./stress_new/Stress_u37.csv
./stress_new/Stress_u38.csv
./stress_new/Stress_u39.csv
<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 5 to 14
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   level      10 non-null     float64
 1   resp_time  10 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1)
memory usage: 240.0 bytes
None
./stress_new/Stress_u40.csv
./stress_new/Stress_u41.csv
<class 'pandas.core.frame.DataFrame'>
Index: 11 entries, 4 to 14
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   level      11 non-null     float64
 1   resp_time  11 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1)
memory usage: 264.0 bytes
None
./stress_new/Stress_u42.csv
<class 'pandas.core.frame.DataFrame'>
Index: 29 entries, 9 to 37
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   level      29 non-null     float64
 1   resp_time  29 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1)
memory usage: 696.0 bytes
None
./stress_new/Stress_u43.csv
<class 'pandas.core.frame.DataFrame'>
Index: 77 entries, 5 to 81
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   level      77 non-null     float64
 1   resp_time  77 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1)
memory usage: 1.8 KB
None
./stress_new/Stress_u44.csv
<class 'pandas.core.frame.DataFrame'>
Index: 87 entries, 5 to 91
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   level      87 non-null     float64
 1   resp_time  87 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1)
memory usage: 2.0 KB
None
./stress_new/Stress_u45.csv
<class 'pandas.core.frame.DataFrame'>
Index: 28 entries, 2 to 32
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   level      28 non-null     float64
 1   resp_time  28 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1)
memory usage: 672.0 bytes
None
./stress_new/Stress_u46.csv
<class 'pandas.core.frame.DataFrame'>
Index: 33 entries, 1 to 37
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   level      33 non-null     float64
 1   resp_time  33 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1)
memory usage: 792.0 bytes
None
./stress_new/Stress_u47.csv
<class 'pandas.core.frame.DataFrame'>
Index: 13 entries, 5 to 17
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   level      13 non-null     float64
 1   resp_time  13 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1)
memory usage: 312.0 bytes
None
./stress_new/Stress_u48.csv
./stress_new/Stress_u49.csv
<class 'pandas.core.frame.DataFrame'>
Index: 61 entries, 0 to 65
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   level      61 non-null     float64
 1   resp_time  61 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1)
memory usage: 1.4 KB
None
./stress_new/Stress_u50.csv
<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, 5 to 8
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   level      4 non-null      float64
 1   resp_time  4 non-null      datetime64[ns]
dtypes: datetime64[ns](1), float64(1)
memory usage: 96.0 bytes
None
./stress_new/Stress_u51.csv
<class 'pandas.core.frame.DataFrame'>
Index: 44 entries, 5 to 48
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   level      44 non-null     float64
 1   resp_time  44 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1)
memory usage: 1.0 KB
None
./stress_new/Stress_u52.csv
<class 'pandas.core.frame.DataFrame'>
Index: 41 entries, 6 to 46
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   level      41 non-null     float64
 1   resp_time  41 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1)
memory usage: 984.0 bytes
None
./stress_new/Stress_u53.csv
<class 'pandas.core.frame.DataFrame'>
Index: 38 entries, 0 to 42
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   level      38 non-null     float64
 1   resp_time  38 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1)
memory usage: 912.0 bytes
None
./stress_new/Stress_u54.csv
<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 5 to 24
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   level      20 non-null     float64
 1   resp_time  20 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1)
memory usage: 480.0 bytes
None
./stress_new/Stress_u55.csv
./stress_new/Stress_u56.csv
<class 'pandas.core.frame.DataFrame'>
Index: 19 entries, 6 to 24
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   level      19 non-null     float64
 1   resp_time  19 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1)
memory usage: 456.0 bytes
None
./stress_new/Stress_u57.csv
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   level      67 non-null     int64
 1   resp_time  67 non-null     datetime64[ns]
dtypes: datetime64[ns](1), int64(1)
memory usage: 1.2 KB
None
./stress_new/Stress_u58.csv
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   level      55 non-null     int64
 1   resp_time  55 non-null     datetime64[ns]
dtypes: datetime64[ns](1), int64(1)
memory usage: 1008.0 bytes
None
./stress_new/Stress_u59.csv
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 269 entries, 0 to 268
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   level      269 non-null    int64
 1   resp_time  269 non-null    datetime64[ns]
dtypes: datetime64[ns](1), int64(1)
memory usage: 4.3 KB
None