In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import os

In [4]:
all_file=os.listdir('./')
file=[]
for each_file in all_file:
    try:
        if  each_file.split('.')[1]=='csv':
            file.append(each_file)
    except: continue
file

['16_with_adress.csv',
 '6_with_adress.csv',
 '51_with_adress.csv',
 '48_with_adress.csv',
 '32_with_adress.csv',
 '47_with_adress.csv',
 '9_with_adress.csv',
 '19_with_adress.csv',
 '24_with_adress.csv',
 '59_with_adress.csv',
 '23_with_adress.csv',
 '40_with_adress.csv',
 '35_with_adress.csv',
 '1_with_adress.csv',
 '11_with_adress.csv',
 '58_with_adress.csv',
 '34_with_adress.csv',
 '10_with_adress.csv',
 '57_with_adress.csv',
 '50_with_adress.csv',
 '17_with_adress.csv',
 '33_with_adress.csv',
 '46_with_adress.csv',
 '8_with_adress.csv',
 '18_with_adress.csv',
 '25_with_adress.csv',
 '43_with_adress.csv',
 '20_with_adress.csv',
 '2_with_adress.csv',
 '55_with_adress.csv',
 '36_with_adress.csv',
 '31_with_adress.csv',
 '52_with_adress.csv',
 '5_with_adress.csv',
 '15_with_adress.csv',
 '28_with_adress.csv',
 '44_with_adress.csv',
 '4_with_adress.csv',
 '14_with_adress.csv',
 '53_with_adress.csv',
 '26_with_adress.csv',
 '45_with_adress.csv',
 '42_with_adress.csv',
 '21_with_adress.csv',
 '54_with_adress.csv',
 '13_with_adress.csv',
 '3_with_adress.csv',
 '37_with_adress.csv']

In [14]:
df=None
for f in file:

    data=pd.read_csv(f)
    if df is None:
        df=data
    else:
        df=pd.concat([df,data])
df.shape

(25993, 21)

In [15]:
df=df.drop('Unnamed: 0',axis=1)
df

,tnv,distance,velocity,accelerate,week_date,date,hour in date,min in date,latitude,longitude,time,moving,active,time_difference,address,type,address_type,hall,nation,count
0,16,0.796136,0.000663,5.528720e-07,3,27:03:2013,11,22,43.704040,-72.290589,1364358145,False,0.0,NaN,"Dartmouth College, College Street, Hanover, Gr...",university,amenity,Dartmouth College,us,26.0
1,16,149.069101,0.124121,1.033479e-04,3,27:03:2013,11,42,43.705126,-72.294705,1364359346,True,1.0,1201.0,"Dartmouth College, College Street, Hanover, Gr...",university,amenity,Dartmouth College,us,1.0
2,16,139.556661,0.004847,1.683125e-07,3,27:03:2013,19,42,43.704100,-72.290643,1364388145,True,1.0,28799.0,"Dartmouth College, College Street, Hanover, Gr...",university,amenity,Dartmouth College,us,26.0
3,16,630.146836,0.073572,8.589879e-06,3,27:03:2013,22,5,43.708691,-72.283648,1364396710,True,1.0,8565.0,"Class of 1978 Life Sciences Center, 78, Colleg...",university,building,Class of 1978 Life Sciences Center,us,10.0
4,16,48.878664,0.020400,8.514236e-06,3,27:03:2013,22,45,43.709047,-72.284392,1364399106,True,1.0,2396.0,"Dewey Field Road, Hanover, Grafton County, New...",bicycle_parking,amenity,NaN,us,23.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
244,37,36.292250,0.060487,1.008118e-04,6,01:06:2013,4,53,43.706916,-72.286891,1370037235,True,1.0,600.0,"Sudikoff Hall, 9, Maynard Street, Hanover, Gra...",university,building,Sudikoff Hall,us,8.0
245,37,37.788414,0.062981,1.049678e-04,6,01:06:2013,5,3,43.706641,-72.287053,1370037835,True,1.0,600.0,"Sudikoff Hall, 9, Maynard Street, Hanover, Gra...",university,building,Sudikoff Hall,us,25.0
246,37,37.431521,0.062386,1.039764e-04,6,01:06:2013,8,3,43.706961,-72.286964,1370048635,True,1.0,10800.0,"Sudikoff Hall, 9, Maynard Street, Hanover, Gra...",university,building,Sudikoff Hall,us,8.0
247,37,40.698375,0.016958,7.065690e-06,6,01:06:2013,8,43,43.706664,-72.287205,1370051035,True,1.0,2400.0,"Sudikoff Hall, 9, Maynard Street, Hanover, Gra...",university,building,Sudikoff Hall,us,2.0
248,37,0.892208,0.001487,2.478356e-06,6,01:06:2013,9,3,43.706627,-72.287065,1370052235,False,0.0,1200.0,"Sudikoff Hall, 9, Maynard Street, Hanover, Gra...",university,building,Sudikoff Hall,us,25.0